[package]
name = "qualify-perfect-arithmetic"
version = "0.0.0"
edition = "2024"
rust-version = "1.99"
publish = false

[features]
default = ["std"]
std = ["perfect-arithmetic/std"]
high-throughput = ["perfect-arithmetic/high-throughput"]

[dependencies]
perfect-arithmetic = { git = "https://github.com/Perfect-Foundations/perfect-arithmetic.git", rev = "0e61fb6854a6c9b5052d4c1deca71b606f1ba7b6", version = "=0.1.0", default-features = false }
